name: Build
run-name: Build
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
on:
  - push
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Set up Clang
        uses: egor-tensin/setup-clang@v1
        with:
          version: latest
      - name: Setup mold
        uses: rui314/setup-mold@v1
        with:
          mold-version: 2.37.1
      - name: Build
        run: BUILD_TYPE=RelWithDebInfo ./build
      - name: Create Linux archive
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          tar -czf buxn-dbg-linux-amd64.tar.gz -C bin/RelWithDebInfo buxn-dbg
      - name: Upload Linux artifact
        if: startsWith(github.ref, 'refs/tags/v')
        uses: actions/upload-artifact@v4
        with:
          name: linux
          path: buxn-dbg-linux-amd64.tar.gz
